/**
 * The root file that combines all of our resolvers
 * ⚠️ DO NOT EDIT THIS FILE ⚠️
 */
import {
  getRecipe,
  getRecipes
} from '../models/Recipe';
import {
  getIngredient,
  getIngredients
} from '../models/Ingredient';

export default {
  Recipe: {
    ingredients: ({ ingredients }) => {
      return Promise.all(
        ingredients.map(ingredient => getIngredient(ingredient))
      );
    }
  },
  Query: {
    recipe: (_, args) => getRecipe(args.id),
    recipes: (_, args) => getRecipes(args),
    ingredient: (_, args) => getIngredient(args.id),
    ingredients: (_, args) => getIngredients(args)
  },
};
